spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git: #使用git的方式
          uri: https://github.com/acerhp/microservice-study-config.git
server:
  port: 8888
    